server:
  port: 80 #\u542F\u52A8\u7AEF\u53E380
#  servlet:
#    context-path: /apis  #  项目的上下文路径，如果有nginx代理的话，这个是需要配置为nginx代理服务器的路径m
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.1.8:3306/demo_db?serverTimezone=Asia/Shanghai  # 数据库的时区地址
    url: jdbc:mysql://120.25.223.121:3306/shangou_db?serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
  messages:
    basename: i18n/validate  #验证文件的路径
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #统一进行日期格式的数据返回
    time-zone: Asia/Shanghai   # 默认时区
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 下划线转换程驼峰
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #  日志也可以这么配置
  mapper-locations: classpath*:mybatis/mapper/**/*.xml  # mapper.xml文件的路径配置
---
logging:
  level:
    com.lh.shangou.dao: info  #  线上环境是info
spring:
  profiles: pro
---
logging:
  level:
    com.lh.shangou.dao: trace  #   开发环境的时候，dao包输出的日志级别是trace
spring:
  profiles: dev


